### ISSUE TITLE
No connection when creating account

### ISSUE THREAD

**Issue by Valdnet** [deependhulla/opensync#15]
No connection to the Nextcloud calendar when setting up the account.
Logs:
```
--- BEGIN DEBUG INFO ---

LOGS:
2020-01-25 14:14:43 1 [ui.setup.DavResourceFinder] Finding initial carddav service configuration
2020-01-25 14:14:43 1 [ui.setup.DavResourceFinder] Checking user-given URL: http://cloud.xxx.pl/
2020-01-25 14:14:43 1 [HttpClient$1] --> PROPFIND http://cloud.xxx.pl/ http/1.1
2020-01-25 14:14:43 1 [HttpClient$1] Content-Type: application/xml; charset=utf-8
2020-01-25 14:14:43 1 [HttpClient$1] Content-Length: 290
2020-01-25 14:14:43 1 [HttpClient$1] Depth: 0
2020-01-25 14:14:43 1 [HttpClient$1] 
2020-01-25 14:14:43 1 [HttpClient$1] <?xml version='1.0' encoding='UTF-8' ?><propfind xmlns="DAV:" xmlns:CAL="urn:ietf:params:xml:ns:caldav" xmlns:CARD="urn:ietf:params:xml:ns:carddav"><prop><resourcetype /><displayname /><CARD:addressbook-description /><CARD:addressbook-home-set /><current-user-principal /></prop></propfind>
2020-01-25 14:14:43 1 [HttpClient$1] --> END PROPFIND (290-byte body)
2020-01-25 14:14:43 1 [HttpClient$1] <-- 405 Method Not Allowed http://cloud.xxx.pl/ (163ms)
2020-01-25 14:14:43 1 [HttpClient$1] date: Sat, 25 Jan 2020 13:14:43 GMT
2020-01-25 14:14:43 1 [HttpClient$1] server: Apache
2020-01-25 14:14:43 1 [HttpClient$1] allow: OPTIONS,HEAD,GET,POST,TRACE
2020-01-25 14:14:43 1 [HttpClient$1] content-length: 359
2020-01-25 14:14:43 1 [HttpClient$1] content-type: text/html; charset=iso-8859-1
2020-01-25 14:14:43 1 [HttpClient$1] 
2020-01-25 14:14:43 1 [HttpClient$1] <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>405 Method Not Allowed</title>
</head><body>
<h1>Method Not Allowed</h1>
<p>The requested method GET is not allowed for the URL /index.html.</p>
<p>Additionally, a 405 Method Not Allowed
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>

2020-01-25 14:14:43 1 [HttpClient$1] <-- END HTTP (359-byte body)
2020-01-25 14:14:43 1 [ui.setup.DavResourceFinder] PROPFIND/OPTIONS on user-given URL failed
EXCEPTION at.bitfire.dav4android.exception.HttpException: 405 Method Not Allowed
	at at.bitfire.dav4android.DavResource.checkStatus(DavResource.java:325)
	at at.bitfire.dav4android.DavResource.checkStatus(DavResource.java:298)
	at at.bitfire.dav4android.DavResource.propfind(DavResource.java:283)
	at com.deependhulla.opensync.ui.setup.DavResourceFinder.checkUserGivenURL(DavResourceFinder.java:179)
	at com.deependhulla.opensync.ui.setup.DavResourceFinder.findInitialConfiguration(DavResourceFinder.java:119)
	at com.deependhulla.opensync.ui.setup.DavResourceFinder.findInitialConfiguration(DavResourceFinder.java:90)
	at com.deependhulla.opensync.ui.setup.DetectConfigurationFragment$ServerConfigurationLoader.loadInBackground(DetectConfigurationFragment.java:142)
	at com.deependhulla.opensync.ui.setup.DetectConfigurationFragment$ServerConfigurationLoader.loadInBackground(DetectConfigurationFragment.java:125)
	at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:302)
	at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:57)
	at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:45)
	at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

2020-01-25 14:14:43 1 [HttpClient$1] --> PROPFIND http://cloud.xxx.pl/.well-known/carddav http/1.1
2020-01-25 14:14:43 1 [HttpClient$1] Content-Type: application/xml; charset=utf-8
2020-01-25 14:14:43 1 [HttpClient$1] Content-Length: 198
2020-01-25 14:14:43 1 [HttpClient$1] Depth: 0
2020-01-25 14:14:43 1 [HttpClient$1] 
2020-01-25 14:14:43 1 [HttpClient$1] <?xml version='1.0' encoding='UTF-8' ?><propfind xmlns="DAV:" xmlns:CAL="urn:ietf:params:xml:ns:caldav" xmlns:CARD="urn:ietf:params:xml:ns:carddav"><prop><current-user-principal /></prop></propfind>
2020-01-25 14:14:43 1 [HttpClient$1] --> END PROPFIND (198-byte body)
2020-01-25 14:14:43 1 [HttpClient$1] <-- 500 Internal Server Error http://cloud.xxx.pl/.well-known/carddav (50ms)
2020-01-25 14:14:43 1 [HttpClient$1] date: Sat, 25 Jan 2020 13:14:43 GMT
2020-01-25 14:14:43 1 [HttpClient$1] server: Apache
2020-01-25 14:14:43 1 [HttpClient$1] content-length: 668
2020-01-25 14:14:43 1 [HttpClient$1] content-type: text/html; charset=iso-8859-1
2020-01-25 14:14:43 1 [HttpClient$1] 
2020-01-25 14:14:43 1 [HttpClient$1] <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at 
 webmaster@cloud.xxx.pl to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
<p>Additionally, a 500 Internal Server Error
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>

2020-01-25 14:14:43 1 [HttpClient$1] <-- END HTTP (668-byte body)
2020-01-25 14:14:43 1 [ui.setup.DavResourceFinder] Well-known URL detection failed
EXCEPTION at.bitfire.dav4android.exception.HttpException: 500 Internal Server Error
	at at.bitfire.dav4android.DavResource.checkStatus(DavResource.java:325)
	at at.bitfire.dav4android.DavResource.checkStatus(DavResource.java:298)
	at at.bitfire.dav4android.DavResource.propfind(DavResource.java:283)
	at com.deependhulla.opensync.ui.setup.DavResourceFinder.getCurrentUserPrincipal(DavResourceFinder.java:352)
	at com.deependhulla.opensync.ui.setup.DavResourceFinder.findInitialConfiguration(DavResourceFinder.java:123)
	at com.deependhulla.opensync.ui.setup.DavResourceFinder.findInitialConfiguration(DavResourceFinder.java:90)
	at com.deependhulla.opensync.ui.setup.DetectConfigurationFragment$ServerConfigurationLoader.loadInBackground(DetectConfigurationFragment.java:142)
	at com.deependhulla.opensync.ui.setup.DetectConfigurationFragment$ServerConfigurationLoader.loadInBackground(DetectConfigurationFragment.java:125)
	at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:302)
	at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:57)
	at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:45)
	at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

2020-01-25 14:14:43 1 [ui.setup.DavResourceFinder] Finding initial caldav service configuration
2020-01-25 14:14:43 1 [ui.setup.DavResourceFinder] Checking user-given URL: http://cloud.xxx.pl/
2020-01-25 14:14:43 1 [HttpClient$1] --> PROPFIND http://cloud.xxx.pl/ http/1.1
2020-01-25 14:14:43 1 [HttpClient$1] Content-Type: application/xml; charset=utf-8
2020-01-25 14:14:43 1 [HttpClient$1] Content-Length: 435
2020-01-25 14:14:43 1 [HttpClient$1] Depth: 0
2020-01-25 14:14:43 1 [HttpClient$1] 
2020-01-25 14:14:43 1 [HttpClient$1] <?xml version='1.0' encoding='UTF-8' ?><propfind xmlns="DAV:" xmlns:CAL="urn:ietf:params:xml:ns:caldav" xmlns:CARD="urn:ietf:params:xml:ns:carddav"><prop><resourcetype /><displayname /><n0:calendar-color xmlns:n0="http://apple.com/ns/ical/" /><CAL:calendar-description /><CAL:calendar-timezone /><current-user-privilege-set /><CAL:supported-calendar-component-set /><CAL:calendar-home-set /><current-user-principal /></prop></propfind>
2020-01-25 14:14:43 1 [HttpClient$1] --> END PROPFIND (435-byte body)
2020-01-25 14:14:43 1 [HttpClient$1] <-- 405 Method Not Allowed http://cloud.xxx.pl/ (45ms)
2020-01-25 14:14:43 1 [HttpClient$1] date: Sat, 25 Jan 2020 13:14:43 GMT
2020-01-25 14:14:43 1 [HttpClient$1] server: Apache
2020-01-25 14:14:43 1 [HttpClient$1] allow: OPTIONS,HEAD,GET,POST,TRACE
2020-01-25 14:14:43 1 [HttpClient$1] content-length: 359
2020-01-25 14:14:43 1 [HttpClient$1] content-type: text/html; charset=iso-8859-1
2020-01-25 14:14:43 1 [HttpClient$1] 
2020-01-25 14:14:43 1 [HttpClient$1] <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>405 Method Not Allowed</title>
</head><body>
<h1>Method Not Allowed</h1>
<p>The requested method GET is not allowed for the URL /index.html.</p>
<p>Additionally, a 405 Method Not Allowed
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>

2020-01-25 14:14:43 1 [HttpClient$1] <-- END HTTP (359-byte body)
2020-01-25 14:14:43 1 [ui.setup.DavResourceFinder] PROPFIND/OPTIONS on user-given URL failed
EXCEPTION at.bitfire.dav4android.exception.HttpException: 405 Method Not Allowed
	at at.bitfire.dav4android.DavResource.checkStatus(DavResource.java:325)
	at at.bitfire.dav4android.DavResource.checkStatus(DavResource.java:298)
	at at.bitfire.dav4android.DavResource.propfind(DavResource.java:283)
	at com.deependhulla.opensync.ui.setup.DavResourceFinder.checkUserGivenURL(DavResourceFinder.java:187)
	at com.deependhulla.opensync.ui.setup.DavResourceFinder.findInitialConfiguration(DavResourceFinder.java:119)
	at com.deependhulla.opensync.ui.setup.DavResourceFinder.findInitialConfiguration(DavResourceFinder.java:91)
	at com.deependhulla.opensync.ui.setup.DetectConfigurationFragment$ServerConfigurationLoader.loadInBackground(DetectConfigurationFragment.java:142)
	at com.deependhulla.opensync.ui.setup.DetectConfigurationFragment$ServerConfigurationLoader.loadInBackground(DetectConfigurationFragment.java:125)
	at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:302)
	at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:57)
	at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:45)
	at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

2020-01-25 14:14:43 1 [HttpClient$1] --> PROPFIND http://cloud.xxx.pl/.well-known/caldav http/1.1
2020-01-25 14:14:43 1 [HttpClient$1] Content-Type: application/xml; charset=utf-8
2020-01-25 14:14:43 1 [HttpClient$1] Content-Length: 198
2020-01-25 14:14:43 1 [HttpClient$1] Depth: 0
2020-01-25 14:14:43 1 [HttpClient$1] 
2020-01-25 14:14:43 1 [HttpClient$1] <?xml version='1.0' encoding='UTF-8' ?><propfind xmlns="DAV:" xmlns:CAL="urn:ietf:params:xml:ns:caldav" xmlns:CARD="urn:ietf:params:xml:ns:carddav"><prop><current-user-principal /></prop></propfind>
2020-01-25 14:14:43 1 [HttpClient$1] --> END PROPFIND (198-byte body)
2020-01-25 14:14:43 1 [HttpClient$1] <-- 500 Internal Server Error http://cloud.xxx.pl/.well-known/caldav (54ms)
2020-01-25 14:14:43 1 [HttpClient$1] date: Sat, 25 Jan 2020 13:14:43 GMT
2020-01-25 14:14:43 1 [HttpClient$1] server: Apache
2020-01-25 14:14:43 1 [HttpClient$1] content-length: 668
2020-01-25 14:14:43 1 [HttpClient$1] content-type: text/html; charset=iso-8859-1
2020-01-25 14:14:43 1 [HttpClient$1] 
2020-01-25 14:14:43 1 [HttpClient$1] <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at 
 webmaster@cloud.xxx.pl to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
<p>Additionally, a 500 Internal Server Error
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>

2020-01-25 14:14:43 1 [HttpClient$1] <-- END HTTP (668-byte body)
2020-01-25 14:14:43 1 [ui.setup.DavResourceFinder] Well-known URL detection failed
EXCEPTION at.bitfire.dav4android.exception.HttpException: 500 Internal Server Error
	at at.bitfire.dav4android.DavResource.checkStatus(DavResource.java:325)
	at at.bitfire.dav4android.DavResource.checkStatus(DavResource.java:298)
	at at.bitfire.dav4android.DavResource.propfind(DavResource.java:283)
	at com.deependhulla.opensync.ui.setup.DavResourceFinder.getCurrentUserPrincipal(DavResourceFinder.java:352)
	at com.deependhulla.opensync.ui.setup.DavResourceFinder.findInitialConfiguration(DavResourceFinder.java:123)
	at com.deependhulla.opensync.ui.setup.DavResourceFinder.findInitialConfiguration(DavResourceFinder.java:91)
	at com.deependhulla.opensync.ui.setup.DetectConfigurationFragment$ServerConfigurationLoader.loadInBackground(DetectConfigurationFragment.java:142)
	at com.deependhulla.opensync.ui.setup.DetectConfigurationFragment$ServerConfigurationLoader.loadInBackground(DetectConfigurationFragment.java:125)
	at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:302)
	at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:57)
	at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:45)
	at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)



SOFTWARE INFORMATION
OpenSync version: 1.5.0.3-ose (145) Tue Apr 18 09:03:24 GMT+02:00 2017
Installed from: com.android.vending
JB Workaround installed: no
```

App:
Android 6
OpenSync 1.5.0.3-ose
Nextcloud 18.0.0
Calendar 2.0.1

**Comment by Valdnet** [comment]
Problem solved. CalDAV/CardDAV had to be set on the server.
